name: Release to App Store

on:
  push:
    paths:
      - "ios/**"
      - "assets/**"
      - "lib/**"
      - "pubspec.lock"
      - "pubspec.yaml"
    branches:
      - main
  release:
    types: [released]
  workflow_dispatch:

jobs:
  ios:
    uses: muxable/.github/.github/workflows/flutter-ios.yml@main
    with:
      app-id: 1567720948
    secrets:
      APPSTORE_API_PRIVATE_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
      APPLE_CERTIFICATE_PRIVATE_KEY: ${{ secrets.APPLE_CERTIFICATE_PRIVATE_KEY }}
